---
- name: Revert lab equipment initial configuration
  import_playbook: ../tasks_service/revert_config.yml

- name: Setup student privileges on switches
  hosts: lab_switches
  
  tasks:
    - name: Enable support both IPv4 and IPv6
      cisco.ios.ios_config:
        lines:
          - sdm prefer dual-ipv4-and-ipv6 default
        save_when: changed

    - name: Config privileges
      cisco.ios.ios_config:
        lines:      
          - privilege exec level 15 clear
          - privilege exec level 2 more system:running-config
          - privilege exec level 2 show running-config
          - privilege exec level 2 configure terminal
          - privilege interface level 2 vlan
          - privilege interface level 2 ip default-gateway
          - privilege configure level 2 do
        save_when: changed         

- name: Setup student privileges on routers
  hosts: lab_routers

  tasks:
    - name: Config privileges
      cisco.ios.ios_config:
        lines:
          - privilege exec level 15 clear
          - privilege exec level 2 more system:running-config
          - privilege exec level 2 show running-config
          - privilege exec level 2 configure terminal
          - privilege configure level 2 interface
          - privilege interface level 2 ip address 0.0.0.0 0.0.0.0 secondary
          - privilege configure level 2 do
        save_when: changed