---

- name: Revert lab equipment initial configuration
  import_playbook: ../tasks_service/revert_config.yml

- name: Enable support both IPv4 and IPv6 on switches 
  hosts: lab_switches
  
  tasks:
    - name: Enable support both IPv4 and IPv6
      cisco.ios.ios_config:
        lines:
          - sdm prefer dual-ipv4-and-ipv6 default
        save_when: changed    

- name: Setup student privileges
  hosts: lab_equipment

  tasks:
    - name: Config privileges
      cisco.ios.ios_config:
        lines:
          - privilege exec level 15 clear
          - privilege exec level 2 more system:running-config
          - privilege exec level 2 show running-config
          - privilege exec level 2 configure terminal
          - privilege configure level 2 interface
          - privilege interface level 2 ipv6 address
          - privilege configure level 2 ipv6 unicast-routing
          - privilege configure level 2 do
        save_when: changed