---
  
- name: Setup student privileges
  hosts: lab_routers

  tasks:
    - name: Config privileges
      cisco.ios.ios_config:
        lines:
          - privilege exec level 15 clear
          - privilege exec level 2 more system:running-config
          - privilege exec level 2 show running-config
          - privilege exec level 2 configure terminal
          - privilege configure level 2 interface
          - privilege interface level 2 ip address 0.0.0.0 0.0.0.0 secondary
          - privilege configure level 2 ip route
          - privilege configure level 2 do
        save_when: changed