---

  - name: Revert lab equipment initial configuration
    hosts: lab_equipment

    tasks:
      - name: Copy startup-config to running-config
        cisco.ios.ios_command:
          commands: 
            - command: copy startup-config running-config
              prompt: Destination filename [running-config]?
              answer: "
              "