---

- name: Adding server key
  hosts: routers
  gather_facts: false

  vars_prompt:
    - name: password
      prompt: "{{ ansible_host }} password"
      private: yes
  
  tasks:
    - name: Send Ansible server key
      cisco.ios.ios_user:
        provider:
          username: ansible
          password: {{ password }}
          authorized: yes
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

