---

- name: Backup config and vlans 
  hosts: all

  tasks:
    - name: Save configs to ./backup/ dir
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: ./backup/{{ inventory_hostname }}
          filename: "{{ inventory_hostname }}.backup"

    - name: Get vlans from switches
      cisco.ios.ios_command:
        commands: show vlan
      register: vlan
      when: inventory_hostname in groups["lab_switches"]

    - name: Save vlan.dat file
      local_action: copy content={{ vlan }} dest=./backup/{{ inventory_hostname }}/vlan.dat
      when: vlan.stdout != ""
      