---

- name: Backup config and vlans 
  hosts: all

  tasks:
    - name: Save configs to ./backup/ dir
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: ./backup/{{ inventory_hostname }}
          filename: "{{ inventory_hostname }}.backup"

    - name: Create vlan.dat file
      local_action: command touch {{ inventory_dir }}/backup/{{ inventory_hostname }}/vlan.dat
      when: inventory_hostname in groups["lab_switches"]

    - name: Save vlans from switches
      cisco.ios.ios_vlans:
        running_config: "{{ lookup('file', '{{ inventory_dir }}/backup/{{ inventory_hostname }}/vlan.dat') }}"
        state: parsed
      when: inventory_hostname in groups["lab_switches"]
      