---

- name: Backup config and vlans 
  hosts: all

  tasks:
    - name: Save configs to ./backup/ dir
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: ./backup/{{ inventory_hostname }}
          filename: "{{ inventory_hostname }}.backup"

    - name: Getting vlan.dat from switches
      cisco.ios.ios_vlans:
        running_config: "{{ lookup('file', './backup/{{ inventory_hostname }}/vlan.dat') }}"
        state: parsed
      when: inventory_hostname in groups["lab_switches"]
      