---

- name: Change passwords
  hosts: all

  vars_prompt:
    - name: new_password
      prompt: Type new password
      private: yes  

  tasks:
    - name: Change default password
      cisco.ios.ios_user:
        name: ansible
        privilege: 15
        configured_password: "{{ new_password }}"
        password_type: secret

