---

- name: Ping from devices
  hosts: all

  tasks:
    - name: Ping 8.8.8.8
      cisco.ios.ios_ping:
        dest: 8.8.8.8
        state: present
      register: output

    - name: Print information
      debug: var=output.rtt
